// <auto-generated />
using System;
using JellyfinMod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyfinMod.Data.Migrations
{
    [DbContext(typeof(ModDbContext))]
    [Migration("20260919071544_PhaseFourAcquisition")]
    partial class PhaseFourAcquisition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionDownloadClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSecretRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedLibraryIds")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcquisitionDownloadClients");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionIndexer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeySecretRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CapabilitiesFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadHosts")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinimumSeedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinimumSeedRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerifiedRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcquisitionIndexers");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionQualityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaximumBytesPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumBytesPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcquisitionQualityProfiles");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultQualityProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefaultQualityProfileId");

                    b.HasIndex("DownloadClientId");

                    b.ToTable("AcquisitionSettings");
                });

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenceAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("TargetId", "UserId")
                        .IsUnique();

                    b.ToTable("CompletionObservations");
                });

            modelBuilder.Entity("JellyfinMod.Data.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("QualityProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReclaimAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("QualityProfileId");

                    b.HasIndex("State");

                    b.HasIndex("MediaType", "TmdbId", "TargetLibraryId")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EntryBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "TmdbId")
                        .IsUnique();

                    b.HasIndex("EntryId", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EpisodeBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservedEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EpisodeConflicts");
                });

            modelBuilder.Entity("JellyfinMod.Data.GrabOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveHash")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveTarget")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadClientRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoldUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceGuid")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveHash")
                        .IsUnique();

                    b.HasIndex("ActiveTarget")
                        .IsUnique();

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("State");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("GrabOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.HistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("JellyfinMod.Data.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncompleteLibraries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnchangedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedBindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReconciliationRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaselineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionBasisAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EligibleAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresFreshCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deadline");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("TargetId")
                        .IsUnique();

                    b.ToTable("RetentionEvaluations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("HardlinkCountBefore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LogicalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalIdentity")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PhysicalIdentity");

                    b.HasIndex("PreparedAt");

                    b.HasIndex("BindingId", "State");

                    b.ToTable("RetentionOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionPolicySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExemptFavourites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SelectedUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedUserMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RetentionPolicySnapshots");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Eligible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inspected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interrupted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LogicalBytesUnlinked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalBytesUnknown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reclaimed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("RetentionRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionSettings", b =>
                {
                    b.HasOne("JellyfinMod.Data.AcquisitionQualityProfile", null)
                        .WithMany()
                        .HasForeignKey("DefaultQualityProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JellyfinMod.Data.AcquisitionDownloadClient", null)
                        .WithMany()
                        .HasForeignKey("DownloadClientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeConflict", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.GrabOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
