// <auto-generated />
using System;
using JellyfinMod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyfinMod.Data.Migrations
{
    [DbContext(typeof(ModDbContext))]
    [Migration("20260919001958_PhaseThreeRetentionBaseline")]
    partial class PhaseThreeRetentionBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenceAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("TargetId", "UserId")
                        .IsUnique();

                    b.ToTable("CompletionObservations");
                });

            modelBuilder.Entity("JellyfinMod.Data.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReclaimAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("State");

                    b.HasIndex("MediaType", "TmdbId", "TargetLibraryId")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EntryBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "TmdbId")
                        .IsUnique();

                    b.HasIndex("EntryId", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EpisodeBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.HistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("JellyfinMod.Data.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncompleteLibraries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnchangedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedBindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReconciliationRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaselineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionBasisAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EligibleAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresFreshCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deadline");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("TargetId")
                        .IsUnique();

                    b.ToTable("RetentionEvaluations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("HardlinkCountBefore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LogicalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalIdentity")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PhysicalIdentity");

                    b.HasIndex("PreparedAt");

                    b.HasIndex("BindingId", "State");

                    b.ToTable("RetentionOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionPolicySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExemptFavourites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SelectedUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedUserMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RetentionPolicySnapshots");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Eligible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inspected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interrupted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LogicalBytesUnlinked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalBytesUnknown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reclaimed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("RetentionRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
