// <auto-generated />
using System;
using JellyfinMod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyfinMod.Data.Migrations
{
    [DbContext(typeof(ModDbContext))]
    [Migration("20260924083528_PhaseTenFirstEnabled")]
    partial class PhaseTenFirstEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionDownloadClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSecretRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedLibraryIds")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcquisitionDownloadClients");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionIndexer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminOverridesJson")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeySecretRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutomateTitleMatches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CapabilitiesFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyQueryBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadHosts")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumSeedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinimumSeedRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProwlarrIndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProwlarrRemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProwlarrSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerifiedRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProwlarrSourceId");

                    b.ToTable("AcquisitionIndexers");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionQualityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cutoff")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaximumBytesPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumAutoScore")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumBytesPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpgradeMode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcquisitionQualityProfiles");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutomationBatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyAutoGrabBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionLogCap")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultQualityProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveryRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DiscoveryVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscoveryVerifiedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EpisodeUpgradesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FreeSpaceFloorBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeSpaceFloorPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImportEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportPollSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentImports")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewEpisodeDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QueueVisibleToUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReacquireReclaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeedFloorHours")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SeedFloorRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("SeedProtectionPasswordRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeedProtectionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedProtectionRpcUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedProtectionSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedProtectionUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SeedReleaseEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SetupCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SetupDismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StalledAfterHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbReadAccessTokenRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoExtensions")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultQualityProfileId");

                    b.HasIndex("DownloadClientId");

                    b.ToTable("AcquisitionSettings");
                });

            modelBuilder.Entity("JellyfinMod.Data.AutomationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GrabId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntryId");

                    b.HasIndex("RunId");

                    b.ToTable("AutomationDecisions");
                });

            modelBuilder.Entity("JellyfinMod.Data.AutomationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Grabbed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueriesByIndexerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Searched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetsConsidered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("UpgradesPlanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("AutomationRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.AutomationTargetState", b =>
                {
                    b.Property<Guid>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDateSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoGrabAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastGrabId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOutcome")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextSearchAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileRevisionSeen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SearchNowRequestedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TargetId");

                    b.HasIndex("EntryId");

                    b.HasIndex("NextSearchAt");

                    b.ToTable("AutomationTargets");
                });

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenceAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("TargetId", "UserId")
                        .IsUnique();

                    b.ToTable("CompletionObservations");
                });

            modelBuilder.Entity("JellyfinMod.Data.DownloadClientPathMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPathPrefix")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPathPrefix")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadClientId", "Order")
                        .IsUnique();

                    b.ToTable("DownloadClientPathMappings");
                });

            modelBuilder.Entity("JellyfinMod.Data.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("QualityProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReclaimAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JellyfinItemId");

                    b.HasIndex("QualityProfileId");

                    b.HasIndex("State");

                    b.HasIndex("MediaType", "TmdbId", "TargetLibraryId")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EntryBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" <> 0");

                    b.HasIndex("EntryId", "SeasonNumber", "EpisodeNumber");

                    b.HasIndex(new[] { "EntryId", "SeasonNumber", "EpisodeNumber" }, "IX_Episodes_EntryId_Position")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" = 0");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EpisodeBindings");
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservedEpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JellyfinItemId")
                        .IsUnique();

                    b.ToTable("EpisodeConflicts");
                });

            modelBuilder.Entity("JellyfinMod.Data.GrabOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveHash")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveTarget")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Automatic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadClientRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoldUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceGuid")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpgradeOperationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveHash")
                        .IsUnique();

                    b.HasIndex("ActiveTarget")
                        .IsUnique();

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("State");

                    b.HasIndex("Automatic", "CreatedAt");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("GrabOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.HistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("JellyfinMod.Data.ImportOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BindingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BoundAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientStatus")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDownloadAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPhysicalIdentity")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRoot")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownloadRateBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EtaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GrabId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HardlinkCountAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryReason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastProgressAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NativeItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenGrabKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RetryOfId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScanRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceClientPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocalPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceLogicalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMountIdentity")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePhysicalIdentity")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StalledSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("GrabId");

                    b.HasIndex("InfoHash");

                    b.HasIndex("OpenGrabKey")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("ImportOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.IndexerBudgetState", b =>
                {
                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BreakerOpenUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastQueryAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueriesUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("IndexerId");

                    b.ToTable("IndexerBudgets");
                });

            modelBuilder.Entity("JellyfinMod.Data.ProwlarrSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeySecretRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveEmptySyncs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEmptySyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncOutcome")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProwlarrSources");
                });

            modelBuilder.Entity("JellyfinMod.Data.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncompleteLibraries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnchangedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedBindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReconciliationRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.ReleaseBlocklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGuid")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash");

                    b.HasIndex("IndexerId", "SourceGuid");

                    b.ToTable("ReleaseBlocklist");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaselineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletionBasisAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EligibleAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresFreshCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deadline");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("TargetId")
                        .IsUnique();

                    b.ToTable("RetentionEvaluations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("HardlinkCountBefore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JellyfinItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LogicalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalIdentity")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpgradeOperationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PhysicalIdentity");

                    b.HasIndex("PreparedAt");

                    b.HasIndex("BindingId", "State");

                    b.ToTable("RetentionOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionPolicySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExemptFavourites")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstEnabledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReclaimAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SelectedUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedUserMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RetentionPolicySnapshots");
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Eligible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inspected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interrupted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LogicalBytesUnlinked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalBytesUnknown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reclaimed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("RetentionRuns");
                });

            modelBuilder.Entity("JellyfinMod.Data.SeedReleaseOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditedRetentionOperationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GoalMetAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GoalRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("GoalRatioSource")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GoalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalSecondsSource")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrabId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HardlinkCountBefore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportOperationId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("IndexerRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("IndexerSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ObservedRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("ObservedSeedingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PhysicalBytesReleased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovingAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedingPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedingPhysicalIdentity")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceLogicalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportOperationId")
                        .IsUnique();

                    b.HasIndex("SeedingPhysicalIdentity");

                    b.HasIndex("State");

                    b.ToTable("SeedReleaseOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.UpgradeOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NewGrabId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NewImportOperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewQuality")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenTargetKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacementRetentionOperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupersededBindingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersededQuality")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("NewGrabId");

                    b.HasIndex("OpenTargetKey")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("UpgradeOperations");
                });

            modelBuilder.Entity("JellyfinMod.Data.VersionKeep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaPath")
                        .IsUnique();

                    b.HasIndex("PhysicalIdentity");

                    b.ToTable("VersionKeeps");
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionIndexer", b =>
                {
                    b.HasOne("JellyfinMod.Data.ProwlarrSource", null)
                        .WithMany()
                        .HasForeignKey("ProwlarrSourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JellyfinMod.Data.AcquisitionSettings", b =>
                {
                    b.HasOne("JellyfinMod.Data.AcquisitionQualityProfile", null)
                        .WithMany()
                        .HasForeignKey("DefaultQualityProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JellyfinMod.Data.AcquisitionDownloadClient", null)
                        .WithMany()
                        .HasForeignKey("DownloadClientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JellyfinMod.Data.AutomationTargetState", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.CompletionObservation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.DownloadClientPathMapping", b =>
                {
                    b.HasOne("JellyfinMod.Data.AcquisitionDownloadClient", null)
                        .WithMany()
                        .HasForeignKey("DownloadClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EntryBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.Episode", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeBinding", b =>
                {
                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.EpisodeConflict", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.GrabOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("JellyfinMod.Data.ImportOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.GrabOperation", null)
                        .WithMany()
                        .HasForeignKey("GrabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.IndexerBudgetState", b =>
                {
                    b.HasOne("JellyfinMod.Data.AcquisitionIndexer", null)
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionEvaluation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JellyfinMod.Data.RetentionOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("JellyfinMod.Data.SeedReleaseOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.ImportOperation", null)
                        .WithMany()
                        .HasForeignKey("ImportOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.UpgradeOperation", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JellyfinMod.Data.VersionKeep", b =>
                {
                    b.HasOne("JellyfinMod.Data.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JellyfinMod.Data.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
