using JellyfinMod.Data;

namespace JellyfinMod.Api.Contracts;

/// <summary>Admin-only retention preview generated by the execution evaluator.</summary>
/// <param name="GeneratedAt">When the protections were evaluated in UTC.</param>
/// <param name="Inspected">Number of physical representations inspected.</param>
/// <param name="Due">Number of representations currently eligible for reclamation.</param>
/// <param name="Blocked">Number of representations blocked by a policy or safety check.</param>
/// <param name="Scheduled">Number of representations with a future deadline.</param>
/// <param name="Waiting">Number of representations waiting for completion evidence.</param>
/// <param name="Disabled">Number of representations excluded by disabled retention policy.</param>
/// <param name="Items">Per-representation diagnostics, including admin-only paths.</param>
public sealed record RetentionPreviewDto(
    DateTime GeneratedAt,
    int Inspected,
    int Due,
    int Blocked,
    int Scheduled,
    int Waiting,
    int Disabled,
    IReadOnlyList<RetentionRepresentationDto> Items);

/// <summary>One physical media representation in an admin retention preview.</summary>
/// <param name="BindingId">The durable binding identity.</param>
/// <param name="EntryId">The catalog entry identity.</param>
/// <param name="EpisodeId">The episode identity, or null for a movie.</param>
/// <param name="JellyfinItemId">The current native media identity.</param>
/// <param name="TargetLibraryId">The native library identity.</param>
/// <param name="Path">The admin-only configured media path.</param>
/// <param name="CanonicalPath">The resolved path after storage checks.</param>
/// <param name="State">Disabled, waiting, scheduled, blocked or due.</param>
/// <param name="Reason">A stable machine-readable reason.</param>
/// <param name="Deadline">The current retention deadline in UTC.</param>
/// <param name="LogicalBytes">The representation's logical byte size.</param>
/// <param name="HardlinkCount">The current inode hardlink count.</param>
/// <param name="TorrentManaged">True for a matched torrent, false for a verified non-torrent, or null when unknown.</param>
/// <param name="UploadRatio">The lowest matched torrent upload ratio.</param>
/// <param name="RatioGoal">The highest matched torrent ratio goal.</param>
/// <param name="SecondsSeeding">The lowest matched torrent cumulative seeding time.</param>
public sealed record RetentionRepresentationDto(
    Guid BindingId,
    Guid EntryId,
    Guid? EpisodeId,
    Guid JellyfinItemId,
    Guid TargetLibraryId,
    string? Path,
    string? CanonicalPath,
    string State,
    string Reason,
    DateTime? Deadline,
    ulong? LogicalBytes,
    uint? HardlinkCount,
    bool? TorrentManaged,
    double? UploadRatio,
    double? RatioGoal,
    long? SecondsSeeding);

/// <summary>One durable automatic or administrator-triggered retention run.</summary>
public sealed record RetentionRunDto(
    Guid Id,
    DateTime StartedAt,
    DateTime? CompletedAt,
    string Status,
    int Inspected,
    int Eligible,
    int Blocked,
    int Reclaimed,
    int Failed,
    int Interrupted,
    long LogicalBytesUnlinked,
    long PhysicalBytesReleased,
    int PhysicalBytesUnknown,
    string? Detail)
{
    /// <summary>Creates the public administrator contract from a durable run.</summary>
    public RetentionRunDto(RetentionRun run)
        : this(run.Id, DateTime.SpecifyKind(run.StartedAt, DateTimeKind.Utc),
            run.CompletedAt.HasValue ? DateTime.SpecifyKind(run.CompletedAt.Value, DateTimeKind.Utc) : null,
            run.Status, run.Inspected, run.Eligible, run.Blocked, run.Reclaimed, run.Failed, run.Interrupted,
            run.LogicalBytesUnlinked, run.PhysicalBytesReleased, run.PhysicalBytesUnknown, run.Detail)
    {
    }
}

/// <summary>Privacy-safe retention state shown with an entry or episode.</summary>
public sealed record RetentionSummaryDto(
    bool Enabled,
    string Policy,
    string State,
    string Reason,
    DateTime? Deadline);
