using System.Text.Json.Serialization;
using JellyfinMod.Data;

namespace JellyfinMod.Api.Contracts;

/// <summary>Admin-only retention preview generated by the execution evaluator.</summary>
/// <param name="GeneratedAt">When the protections were evaluated in UTC.</param>
/// <param name="Inspected">Number of physical representations inspected.</param>
/// <param name="Due">Number of representations currently eligible for reclamation.</param>
/// <param name="Blocked">Number of representations blocked by a policy or safety check.</param>
/// <param name="Scheduled">Number of representations with a future deadline.</param>
/// <param name="Waiting">Number of representations waiting for completion evidence.</param>
/// <param name="Disabled">Number of representations excluded by disabled retention policy.</param>
/// <param name="Items">Per-representation diagnostics, including admin-only paths.</param>
public sealed record RetentionPreviewDto(
    [property: JsonPropertyName("generatedAt")] DateTime GeneratedAt,
    [property: JsonPropertyName("inspected")] int Inspected,
    [property: JsonPropertyName("due")] int Due,
    [property: JsonPropertyName("blocked")] int Blocked,
    [property: JsonPropertyName("scheduled")] int Scheduled,
    [property: JsonPropertyName("waiting")] int Waiting,
    [property: JsonPropertyName("disabled")] int Disabled,
    [property: JsonPropertyName("items")] IReadOnlyList<RetentionRepresentationDto> Items);

/// <summary>One physical media representation in an admin retention preview.</summary>
/// <param name="BindingId">The durable binding identity.</param>
/// <param name="EntryId">The catalog entry identity.</param>
/// <param name="EpisodeId">The episode identity, or null for a movie.</param>
/// <param name="JellyfinItemId">The current native media identity.</param>
/// <param name="TargetLibraryId">The native library identity.</param>
/// <param name="Path">The admin-only configured media path.</param>
/// <param name="CanonicalPath">The resolved path after storage checks.</param>
/// <param name="State">Disabled, waiting, scheduled, blocked or due.</param>
/// <param name="Reason">A stable machine-readable reason.</param>
/// <param name="Deadline">The current retention deadline in UTC.</param>
/// <param name="LogicalBytes">The representation's logical byte size.</param>
/// <param name="HardlinkCount">The current inode hardlink count.</param>
/// <param name="TorrentManaged">True for a matched torrent, false for a verified non-torrent, or null when unknown.</param>
/// <param name="UploadRatio">The lowest matched torrent upload ratio.</param>
/// <param name="RatioGoal">The highest matched torrent ratio goal.</param>
/// <param name="SecondsSeeding">The lowest matched torrent cumulative seeding time.</param>
public sealed record RetentionRepresentationDto(
    [property: JsonPropertyName("bindingId")] Guid BindingId,
    [property: JsonPropertyName("entryId")] Guid EntryId,
    [property: JsonPropertyName("episodeId")] Guid? EpisodeId,
    [property: JsonPropertyName("jellyfinItemId")] Guid JellyfinItemId,
    [property: JsonPropertyName("targetLibraryId")] Guid TargetLibraryId,
    [property: JsonPropertyName("path")] string? Path,
    [property: JsonPropertyName("canonicalPath")] string? CanonicalPath,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("reason")] string Reason,
    [property: JsonPropertyName("deadline")] DateTime? Deadline,
    [property: JsonPropertyName("logicalBytes")] ulong? LogicalBytes,
    [property: JsonPropertyName("hardlinkCount")] uint? HardlinkCount,
    [property: JsonPropertyName("torrentManaged")] bool? TorrentManaged,
    [property: JsonPropertyName("uploadRatio")] double? UploadRatio,
    [property: JsonPropertyName("ratioGoal")] double? RatioGoal,
    [property: JsonPropertyName("secondsSeeding")] long? SecondsSeeding);

/// <summary>One durable automatic or administrator-triggered retention run.</summary>
public sealed record RetentionRunDto(
    [property: JsonPropertyName("id")] Guid Id,
    [property: JsonPropertyName("startedAt")] DateTime StartedAt,
    [property: JsonPropertyName("completedAt")] DateTime? CompletedAt,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("inspected")] int Inspected,
    [property: JsonPropertyName("eligible")] int Eligible,
    [property: JsonPropertyName("blocked")] int Blocked,
    [property: JsonPropertyName("reclaimed")] int Reclaimed,
    [property: JsonPropertyName("failed")] int Failed,
    [property: JsonPropertyName("interrupted")] int Interrupted,
    [property: JsonPropertyName("logicalBytesUnlinked")] long LogicalBytesUnlinked,
    [property: JsonPropertyName("physicalBytesReleased")] long PhysicalBytesReleased,
    [property: JsonPropertyName("physicalBytesUnknown")] int PhysicalBytesUnknown,
    [property: JsonPropertyName("detail")] string? Detail)
{
    /// <summary>Creates the public administrator contract from a durable run.</summary>
    public RetentionRunDto(RetentionRun run)
        : this(run.Id, DateTime.SpecifyKind(run.StartedAt, DateTimeKind.Utc),
            run.CompletedAt.HasValue ? DateTime.SpecifyKind(run.CompletedAt.Value, DateTimeKind.Utc) : null,
            run.Status, run.Inspected, run.Eligible, run.Blocked, run.Reclaimed, run.Failed, run.Interrupted,
            run.LogicalBytesUnlinked, run.PhysicalBytesReleased, run.PhysicalBytesUnknown, run.Detail)
    {
    }
}

/// <summary>Privacy-safe retention state shown with an entry or episode.</summary>
public sealed record RetentionSummaryDto(
    [property: JsonPropertyName("enabled")] bool Enabled,
    [property: JsonPropertyName("policy")] string Policy,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("reason")] string Reason,
    [property: JsonPropertyName("deadline")] DateTime? Deadline);

/// <summary>Builds retention summaries without exposing per-user playback evidence.</summary>
internal static class RetentionSummaries
{
    /// <summary>Builds a movie summary or an access-safe aggregate across a series' episodes.</summary>
    public static RetentionSummaryDto ForEntry(
        Entry entry,
        RetentionPolicySnapshot? policy,
        IEnumerable<RetentionEvaluation> evaluations)
    {
        var rows = evaluations.Where(evaluation => evaluation.EntryId == entry.Id).ToArray();
        if (entry.MediaType == "movie")
            return ForTarget(entry, policy, rows.SingleOrDefault(evaluation => evaluation.TargetId == entry.Id));
        if (entry.RetentionPolicy == RetentionPolicy.Never || policy?.Enabled != true || rows.Length == 0)
            return ForTarget(entry, policy, null);
        var summaries = rows.Select(evaluation => ForTarget(entry, policy, evaluation)).ToArray();
        var first = summaries[0];
        if (summaries.All(summary => summary.State == first.State && summary.Reason == first.Reason))
            return first with { Deadline = Earliest(summaries) };
        return new(true, RetentionPolicies.ToWire(entry.RetentionPolicy), "mixed", "episode_states_vary",
            Earliest(summaries));
    }

    /// <summary>Builds one movie or episode summary from durable policy and evaluation evidence.</summary>
    public static RetentionSummaryDto ForTarget(
        Entry entry,
        RetentionPolicySnapshot? policy,
        RetentionEvaluation? evaluation)
    {
        if (entry.RetentionPolicy == RetentionPolicy.Never)
            return new(policy?.Enabled == true, RetentionPolicies.ToWire(entry.RetentionPolicy),
                "blocked", "kept", null);
        if (policy?.Enabled != true)
            return new(false, RetentionPolicies.ToWire(entry.RetentionPolicy),
                "disabled", "retention_disabled", null);
        return new(true, RetentionPolicies.ToWire(entry.RetentionPolicy),
            evaluation?.State ?? "waiting", evaluation?.Reason ?? "evaluation_missing",
            evaluation?.Deadline is { } deadline ? DateTime.SpecifyKind(deadline, DateTimeKind.Utc) : null);
    }

    private static DateTime? Earliest(IEnumerable<RetentionSummaryDto> summaries) =>
        summaries.Where(summary => summary.Deadline.HasValue).Select(summary => summary.Deadline).Min();
}
